apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: demo-secret
  namespace: secure-lab
spec:
  encryptedData:
    username: REPLACE_WITH_ENCRYPTED_USERNAME
    password: REPLACE_WITH_ENCRYPTED_PASSWORD
  template:
    metadata:
      name: demo-secret
      namespace: secure-lab
    type: Opaque
